### ISSUE TITLE
你好，请问下，你这生成的藏字全么

### ISSUE THREAD

**Issue by daixiangzi** [puntsokCN/print_tibetian#1]

**Comment by daixiangzi** [comment]
因为我看到有的人生成了大概有1.8w个藏字，我看你这才1w多点，或者说你这生成的是常用藏字的？

**Comment by puntsokCN** [comment]
嗯嗯，我这个是根据正字规范找出来的，应该比较全




平措罗布
puntsok@foxmail.com




------------------ 原始邮件 ------------------

**Comment by daixiangzi** [comment]
> 嗯嗯，我这个是根据正字规范找出来的，应该比较全 平措罗布 puntsok@foxmail.com


> 嗯嗯，我这个是根据正字规范找出来的，应该比较全 平措罗布 puntsok@foxmail.com
> […](#)
好的，我试试

**Comment by daixiangzi** [comment]
能留个微信好友么，我还有一点疑问

**Comment by puntsokCN** [comment]
a_gei0629


平措罗布
puntsok@foxmail.com




------------------ 原始邮件 ------------------
